version: '2'
services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    user: 1000:1000
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wp_data:/var/www/html
      - ./wp:/var/www/html/.storage

  wordpress-cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    user: 1000:1000
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    command: >
      /bin/sh -c '
      sleep 10;
      wp core install --path="/var/www/html" --url=localhost --title="Hornburg" --admin_user=theoden --admin_password=secret --admin_email=theoden@webexp.io;
      wp plugin install /var/www/html/.storage/wp-shoutbox-live-chat.zip --activate --force;
      wp plugin install wordpress-importer --activate;
      wp import /var/www/html/.storage/hornburg.xml --authors=create;
      tail -f /dev/null
      '
    volumes:
      - wp_data:/var/www/html
      - ./wp:/var/www/html/.storage

volumes:
  db_data:
  wp_data:

