# to build for other devices, str_replace these strigs with your architecture:
# - ar71xx
# - 1806
# to create your package
# - modify locally the package on ./packages
# - execute /bin/bash on the docker machine (e.g. example1) and:
#    - copy the package file in the correct location: cp -r /tmp/storage/ /root/sdk/sdk/1806/ar71xx/package;
#    - make the package: make package/example1/compile V=s;
#    - copy on host storage the ipk: cp -r /root/sdk/sdk/1806/ar71xx/bin/packages/mips_24kc/base/ /tmp/storage;

version: "2"

services:
  ubuntu18:
    image: ubuntu:18.04
    command: >
      /bin/sh -c '
      apt install bash;
      bash;
      cd /root;
      apt update;
      DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install asciidoc bc binutils bzip2 fastjar flex gawk gcc genisoimage gettext git intltool jikespg libgtk2.0-dev libncurses5-dev libssl1.0-dev make mercurial patch perl-modules python2.7-dev rsync ruby sdcc subversion unzip util-linux wget xsltproc zlib1g-dev zlib1g-dev -y;
      apt install git;
      apt install time;
      git clone https://github.com/gl-inet/sdk.git;
      cd sdk;
      ./download.sh ar71xx-1806;
      cd sdk/1806/ar71xx;
      ./scripts/feeds update -f;
      ./scripts/feeds install -a;
      tail -f /dev/null
      '
    volumes:
      - ./packages:/tmp/storage


